repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --install-types, --non-interactive]

  - repo: local
    hooks:
      - id: pyright
        name: Pyright
        entry: pyright
        language: system
        types: [python]
        args: [pharia_skill]
