[tool.poetry]
name = "pharia-kernel-sdk-py"
version = "0.1.0"
description = ""
authors = ["Jia Ho Lee <jiaho.lee@aleph-alpha.com>"]
readme = "README.md"
packages = [{ include = "pharia_skill" }]

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
