[tool.poetry]
name = "pharia-kernel-sdk-py"
version = "0.2.1"
description = ""
authors = [
    "Peter Barth <peter.barth@aleph-alpha.com>",
    "Markus Klein <markus.klein@aleph-alpha.com>",
    "Benjamin Brandt <benjamin.brandt@aleph-alpha.com>",
    "Daniel Tscherwinka <daniel.tscherwinka@aleph-alpha.com>",
    "Moritz Althaus <moritz.althaus@aleph-alpha.com>",
    "Jia Ho Lee <jiaho.lee@aleph-alpha.com>",
]
readme = "README.md"
packages = [{ include = "pharia_skill" }]

[tool.poetry.dependencies]
python = "^3.11"
pydantic-core = "2.14.5"
pydantic = "2.5.2"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
componentize-py = "^0.14.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
ruff = "^0.6.9"
mypy = "^1.12.1"
pre-commit = "^4.0.1"

[tool.poetry.scripts]
pharia-skill = "pharia_skill.cli:main"

[tool.pytest.ini_options]
markers = ["kernel: marks tests that requires Pharia Kernel"]

[tool.ruff]
exclude = ["pharia_skill/wit"]
lint.extend-select = ["I"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
