[tool.poetry]
name = "pharia-kernel-sdk-py"
version = "0.1.0"
description = ""
authors = [
    "Peter Barth <peter.barth@aleph-alpha.com>",
    "Markus Klein <markus.klein@aleph-alpha.com>",
    "Benjamin Brandt <benjamin.brandt@aleph-alpha.com>",
    "Daniel Tscherwinka <daniel.tscherwinka@aleph-alpha.com>",
    "Moritz Althaus <moritz.althaus@aleph-alpha.com>",
    "Jia Ho Lee <jiaho.lee@aleph-alpha.com>",
]
readme = "README.md"
packages = [{ include = "pharia_skill" }]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
ruff = "^0.6.5"

[tool.ruff]
exclude = ["pharia_skill/wit"]
lint.extend-select = ["I"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
