package pharia:skill@0.4.0;

world message-stream-skill {
    include csi;
    export message-stream;
}

world skill {
    include csi;
    export skill-handler;
}

interface skill-handler {
    /// The set of errors which may be raised by functions in this interface
    variant error {
        internal(string),
        invalid-input(string)
    }

    run: func(input: list<u8>) -> result<list<u8>, error>;

    record skill-metadata {
        description: option<string>,
        input-schema: list<u8>,
        output-schema: list<u8>,
    }

    metadata: func() -> skill-metadata;
}
