name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445
      - if: ${{ steps.release.outputs.release_created }}
        name: Checkout
        uses: actions/checkout@v5
      - if: ${{ steps.release.outputs.release_created }}
        name: Install uv
        uses: astral-sh/setup-uv@7edac99f961f18b581bbd960d59d049f04c0002f
      - if: ${{ steps.release.outputs.release_created }}
        name: Build and publish to Artifactory PyPI repository
        run: |
          uv build
          uv publish
