name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445
      - if: ${{ steps.release.outputs.release_created }}
        name: Checkout
        uses: actions/checkout@v4
      - if: ${{ steps.release.outputs.release_created }}
        name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86
      - if: ${{ steps.release.outputs.release_created }}
        name: Build and publish to Artifactory PyPI repository
        run: |
          uv build
          uv publish
